source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'kaminari', '0.15.1'
gem 'awesome_print'
gem 'quiet_assets'
gem 'capistrano', '~> 3.1.0'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'capistrano-rails', '~> 1.1.1'
gem 'capistrano-rbenv'
gem 'compass'
gem 'rspec-rails'
gem 'guard-rspec'
gem 'capybara'
gem 'spring'
gem 'mysql2'
gem 'forem', :github => "radar/forem", :branch => "rails4"
gem 'devise'
gem 'rails_admin'
gem 'carrierwave'
gem 'forem-bootstrap', :github => "radar/forem-bootstrap"
gem 'slim-rails'
group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'launchy'
end
